name: tutor_helper
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  meta: ">=1.1.0 <2.0.0"
  equatable: ^0.2.0
  flutter_bloc: ^0.18.3
  flutter:
    sdk: flutter
  unicorndial: "^1.1.5"
  json_annotation: ^2.0.0
  path_provider: ^1.1.0
  
  cupertino_icons: ^0.1.2
  intl: ^0.15.8
  flutter_datetime_picker: 
    git:
      url: https://github.com/derohimat/flutter_datetime_picker.git
  flutter_slidable: "^0.5.3"
  #simple_permissions: ^0.1.9
  path: ^1.6.2
  #share: 0.6.3+5
    #git:
    #  url: https://github.com/pboos/plugins.git
    #  path: packages/share
    #  ref: feature/shareFile
  flutter_share_file: 1.1.4+1
  dots_indicator: ^1.0.0
  # image_gallery_saver: ^1.1.0
  image_gallery_saver: 1.2.2
   # path: ./image_gallery_saver-1.1.0
  simple_permissions: 
    path:  ./simple_permissions-0.1.9
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^2.0.0
  flutter_launcher_icons: ^0.7.4


flutter_icons:
  image_path_ios: 'assets/icon/icon.png'
  image_path_android: 'assets/icon/icon.png'
  android: true
  ios: true

flutter:

  uses-material-design: true
  fonts:
    - family: Kanit
      fonts:
        - asset: fonts/Kanit-Thin.ttf
          weight: 100
        - asset: fonts/Kanit-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: fonts/Kanit-ExtraLight.ttf
          weight: 200
        - asset: fonts/Kanit-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: fonts/Kanit-Light.ttf
          weight: 300
        - asset: fonts/Kanit-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/Kanit-Regular.ttf
          weight: 400
        - asset: fonts/Kanit-RegularItalic.ttf
          weight: 400
          style: italic
        - asset: fonts/Kanit-Medium.ttf
          weight: 500
        - asset: fonts/Kanit-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/Kanit-SemiBold.ttf
          weight: 600
        - asset: fonts/Kanit-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: fonts/Kanit-Bold.ttf
          weight: 700
        - asset: fonts/Kanit-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/Kanit-ExtraBold.ttf
          weight: 800
        - asset: fonts/Kanit-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: fonts/Kanit-Black.ttf
          weight: 900
        - asset: fonts/Kanit-BlackItalic.ttf
          weight: 900
          style: italic